Repository WISDEM/WOMBAT, pull requests merged in 2023-10, with the labels that each got.

#118 Bug fix: Task completion rate clarity
  CHANGELOG.md
  wombat/core/post_processor.py
  wombat/core/repair_management.py
  wombat/windfarm/windfarm.py
Labels: bug, enhancement

#120 Bug Fix: Keep logged events within the timing bounds
  CHANGELOG.md
  wombat/core/environment.py
Labels: bug

#121 Feature/basic plotting
  CHANGELOG.md
  wombat/core/environment.py
  wombat/core/post_processor.py
  wombat/core/simulation_api.py
  wombat/utilities/plot.py
  wombat/windfarm/system/system.py
  wombat/windfarm/windfarm.py
Labels: bug, documentation, enhancement

#122 Deprecate `Configuration.library_path`
  CHANGELOG.md
  docs/jupyter_execute/examples/how_to.ipynb
  docs/source/examples/how_to.md
  wombat/core/simulation_api.py
Labels: enhancement

#119 OpEx Breakdown Function
  CHANGELOG.md
  wombat/core/post_processor.py
Labels: enhancement

#124 Update documentation ahead of v0.9 release
  CHANGELOG.md
  LICENSE
  NOTICE
  docs/jupyter_execute/examples/how_to.ipynb
  docs/jupyter_execute/examples/metrics_demonstration.ipynb
  docs/jupyter_execute/examples/strategy_demonstration.ipynb
  docs/source/API/core.md
  docs/source/API/index.md
  docs/source/API/simulation_api.md
  docs/source/API/types.md
  docs/source/API/utilities.md
  docs/source/API/windfarm.md
  docs/source/conf.py
  docs/source/examples/index.md
  docs/source/examples/metrics_demonstration.md
  docs/source/index.rst
  examples/dinwoodie_validation.ipynb
  examples/dinwoodie_validation_100pct_operation_reduction.ipynb
  examples/how_to.ipynb
  examples/iea_26_validation.ipynb
  examples/metrics_demonstration.ipynb
  examples/strategy_demonstration.ipynb
  examples/timing_benchmarks.ipynb
  library/code_comparison/dinwoodie/results/results_data.csv
  library/code_comparison/dinwoodie/results/results_data_100pct_reduction_v0.4.1.csv
  library/code_comparison/dinwoodie/results/results_data_v0.4.1.csv
  library/code_comparison/dinwoodie/results/results_data_v0.4.csv
  library/code_comparison/dinwoodie/results/results_data_v0.5.1.csv
  library/code_comparison/dinwoodie/results/results_dict.pkl
  library/code_comparison/dinwoodie/results/results_dict_100pct_reduction_v0.4.1.yaml
  library/code_comparison/dinwoodie/results/results_dict_v0.4.1.yaml
  library/code_comparison/dinwoodie/results/results_dict_v0.4.yaml
  library/code_comparison/dinwoodie/results/results_dict_v0.5.1.yaml
  library/code_comparison/dinwoodie/vessels/ctv4.yaml
  library/code_comparison/dinwoodie/vessels/ctv5.yaml
  library/code_comparison/dinwoodie/vessels/hlv_1_scheduled.yaml
  library/code_comparison/dinwoodie/vessels/hlv_2_scheduled.yaml
  library/code_comparison/dinwoodie/vessels/hlv_3_scheduled.yaml
  library/code_comparison/iea26/project/config/one_mobilization.yaml
  library/code_comparison/iea26/project/config/two_mobilizations.yaml
  library/code_comparison/iea26/results/results_data.csv
  library/code_comparison/iea26/results/results_data_v0.4.1.csv
  library/code_comparison/iea26/results/results_data_v0.4.csv
  library/code_comparison/iea26/results/results_data_v0.5.1.csv
  library/code_comparison/iea26/results/results_dict.pkl
  library/code_comparison/iea26/results/results_dict_v0.4.1.yaml
  library/code_comparison/iea26/results/results_dict_v0.4.yaml
  library/code_comparison/iea26/results/results_dict_v0.5.1.yaml
  library/code_comparison/iea26/vessels/hlv_1.yaml
  library/code_comparison/iea26/vessels/hlv_2.yaml
  library/code_comparison/iea26/vessels/hlv_3.yaml
  wombat/core/data_classes.py
Labels: documentation
